[package]
name = "libsourcemap"
version = "0.5.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[lib]
name = "libsourcemap"
crate-type = ["cdylib", "rlib"]

[dependencies]
sourcemap = "0.14.0"
error-chain = "0.5.0"
memmap = "0.4.0"
brotli2 = "0.2.1"
varinteger = "1.0.2"
